# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EventsTableDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EventsTableDialog(object):
    def setupUi(self, EventsTableDialog):
        EventsTableDialog.setObjectName("EventsTableDialog")
        EventsTableDialog.setWindowModality(QtCore.Qt.WindowModal)
        EventsTableDialog.resize(620, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EventsTableDialog.sizePolicy().hasHeightForWidth())
        EventsTableDialog.setSizePolicy(sizePolicy)
        EventsTableDialog.setModal(True)
        self.tableEvent = QtWidgets.QTableWidget(EventsTableDialog)
        self.tableEvent.setGeometry(QtCore.QRect(10, 10, 681, 441))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableEvent.setFont(font)
        self.tableEvent.setObjectName("tableEvent")
        self.tableEvent.setColumnCount(4)
        self.tableEvent.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableEvent.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEvent.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEvent.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEvent.setHorizontalHeaderItem(3, item)
        self.tableEvent.horizontalHeader().setDefaultSectionSize(190)
        self.tableEvent.horizontalHeader().setMinimumSectionSize(69)
        self.acceptButton = QtWidgets.QPushButton(EventsTableDialog)
        self.acceptButton.setGeometry(QtCore.QRect(310, 460, 301, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.acceptButton.setFont(font)
        self.acceptButton.setObjectName("acceptButton")
        self.addButton = QtWidgets.QPushButton(EventsTableDialog)
        self.addButton.setGeometry(QtCore.QRect(10, 460, 101, 31))
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(EventsTableDialog)
        self.deleteButton.setGeometry(QtCore.QRect(120, 460, 101, 31))
        self.deleteButton.setObjectName("deleteButton")

        self.retranslateUi(EventsTableDialog)
        QtCore.QMetaObject.connectSlotsByName(EventsTableDialog)

    def retranslateUi(self, EventsTableDialog):
        _translate = QtCore.QCoreApplication.translate
        EventsTableDialog.setWindowTitle(_translate("EventsTableDialog", "Dialog"))
        item = self.tableEvent.horizontalHeaderItem(0)
        item.setText(_translate("EventsTableDialog", "Кадр"))
        item = self.tableEvent.horizontalHeaderItem(1)
        item.setText(_translate("EventsTableDialog", "Время"))
        item = self.tableEvent.horizontalHeaderItem(2)
        item.setText(_translate("EventsTableDialog", "Событие"))
        item = self.tableEvent.horizontalHeaderItem(3)
        item.setText(_translate("EventsTableDialog", "Цвет"))
        self.acceptButton.setText(_translate("EventsTableDialog", "Перейти к выбранному событию"))
        self.addButton.setText(_translate("EventsTableDialog", "Добавить"))
        self.deleteButton.setText(_translate("EventsTableDialog", "Удалить"))
