# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TableDialog(object):
    def setupUi(self, TableDialog):
        TableDialog.setObjectName("TableDialog")
        TableDialog.setWindowModality(QtCore.Qt.WindowModal)
        TableDialog.resize(700, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TableDialog.sizePolicy().hasHeightForWidth())
        TableDialog.setSizePolicy(sizePolicy)
        TableDialog.setModal(True)
        self.tableEvent = QtWidgets.QTableWidget(TableDialog)
        self.tableEvent.setGeometry(QtCore.QRect(10, 10, 681, 431))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tableEvent.setFont(font)
        self.tableEvent.setObjectName("tableEvent")
        self.tableEvent.setColumnCount(4)
        self.tableEvent.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableEvent.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEvent.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEvent.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableEvent.setHorizontalHeaderItem(3, item)
        self.tableEvent.horizontalHeader().setDefaultSectionSize(190)
        self.tableEvent.horizontalHeader().setMinimumSectionSize(69)
        self.acceptButton = QtWidgets.QPushButton(TableDialog)
        self.acceptButton.setGeometry(QtCore.QRect(370, 450, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.acceptButton.setFont(font)
        self.acceptButton.setObjectName("acceptButton")
        self.addButton = QtWidgets.QPushButton(TableDialog)
        self.addButton.setGeometry(QtCore.QRect(10, 450, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.deleteButton = QtWidgets.QPushButton(TableDialog)
        self.deleteButton.setGeometry(QtCore.QRect(60, 450, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.deleteButton.setFont(font)
        self.deleteButton.setObjectName("deleteButton")

        self.retranslateUi(TableDialog)
        QtCore.QMetaObject.connectSlotsByName(TableDialog)

    def retranslateUi(self, TableDialog):
        _translate = QtCore.QCoreApplication.translate
        TableDialog.setWindowTitle(_translate("TableDialog", "Dialog"))
        item = self.tableEvent.horizontalHeaderItem(0)
        item.setText(_translate("TableDialog", "Фрейм"))
        item = self.tableEvent.horizontalHeaderItem(1)
        item.setText(_translate("TableDialog", "Время"))
        item = self.tableEvent.horizontalHeaderItem(2)
        item.setText(_translate("TableDialog", "Событие"))
        item = self.tableEvent.horizontalHeaderItem(3)
        item.setText(_translate("TableDialog", "Цвет"))
        self.acceptButton.setText(_translate("TableDialog", "Перейти на выбранное событие"))
        self.addButton.setText(_translate("TableDialog", "+"))
        self.deleteButton.setText(_translate("TableDialog", "-"))
